USE [MES31]
GO

/****** Object:  Table [dbo].[MaterialTableA]    Script Date: 2026/09/12 13:52:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MaterialTableA](
	[MasterKey] [nvarchar](32) NOT NULL,
	[ForeignKey] [nvarchar](32) NULL,
	[LotNumber] [nvarchar](16) NOT NULL,
	[ItemCode] [nvarchar](16) NOT NULL,
	[DrumcanItemCode01] [nvarchar](16) NULL,
	[DrumcanLotNumber01] [nvarchar](16) NULL,
	[DrumcanLoadingAmount01] [real] NULL,
	[DrumcanItemCode02] [nvarchar](16) NULL,
	[DrumcanLotNumber02] [nvarchar](16) NULL,
	[DrumcanLoadingAmount02] [real] NULL,
	[DrumcanItemCode03] [nvarchar](16) NULL,
	[DrumcanLotNumber03] [nvarchar](16) NULL,
	[DrumcanLoadingAmount03] [real] NULL,
	[DrumcanItemCode04] [nvarchar](16) NULL,
	[DrumcanLotNumber04] [nvarchar](16) NULL,
	[DrumcanLoadingAmount04] [real] NULL,
	[DrumcanItemCode05] [nvarchar](16) NULL,
	[DrumcanLotNumber05] [nvarchar](16) NULL,
	[DrumcanLoadingAmount05] [real] NULL,
	[ManualInputItemCode01] [nvarchar](16) NULL,
	[ManualInputLotNumber01] [nvarchar](16) NULL,
	[ManualInputLoadingAmount01] [real] NULL,
	[ManualInputItemCode02] [nvarchar](16) NULL,
	[ManualInputLotNumber02] [nvarchar](16) NULL,
	[ManualInputLoadingAmount02] [real] NULL,
	[ManualInputItemCode03] [nvarchar](16) NULL,
	[ManualInputLotNumber03] [nvarchar](16) NULL,
	[ManualInputLoadingAmount03] [real] NULL,
	[ManualInputItemCode04] [nvarchar](16) NULL,
	[ManualInputLotNumber04] [nvarchar](16) NULL,
	[ManualInputLoadingAmount04] [real] NULL,
	[ManualInputItemCode05] [nvarchar](16) NULL,
	[ManualInputLotNumber05] [nvarchar](16) NULL,
	[ManualInputLoadingAmount05] [real] NULL,
	[ManualInputItemCode06] [nvarchar](16) NULL,
	[ManualInputLotNumber06] [nvarchar](16) NULL,
	[ManualInputLoadingAmount06] [real] NULL,
	[ManualInputItemCode07] [nvarchar](16) NULL,
	[ManualInputLotNumber07] [nvarchar](16) NULL,
	[ManualInputLoadingAmount07] [real] NULL,
	[ManualInputItemCode08] [nvarchar](16) NULL,
	[ManualInputLotNumber08] [nvarchar](16) NULL,
	[ManualInputLoadingAmount08] [real] NULL,
	[ManualInputItemCode09] [nvarchar](16) NULL,
	[ManualInputLotNumber09] [nvarchar](16) NULL,
	[ManualInputLoadingAmount09] [real] NULL,
	[ManualInputItemCode10] [nvarchar](16) NULL,
	[ManualInputLotNumber10] [nvarchar](16) NULL,
	[ManualInputLoadingAmount10] [real] NULL,
	[ManualInputItemCode11] [nvarchar](16) NULL,
	[ManualInputLotNumber11] [nvarchar](16) NULL,
	[ManualInputLoadingAmount11] [real] NULL,
	[ManualInputItemCode12] [nvarchar](16) NULL,
	[ManualInputLotNumber12] [nvarchar](16) NULL,
	[ManualInputLoadingAmount12] [real] NULL,
	[ManualInputItemCode13] [nvarchar](16) NULL,
	[ManualInputLotNumber13] [nvarchar](16) NULL,
	[ManualInputLoadingAmount13] [real] NULL,
	[ManualInputItemCode14] [nvarchar](16) NULL,
	[ManualInputLotNumber14] [nvarchar](16) NULL,
	[ManualInputLoadingAmount14] [real] NULL,
	[ManualInputItemCode15] [nvarchar](16) NULL,
	[ManualInputLotNumber15] [nvarchar](16) NULL,
	[ManualInputLoadingAmount15] [real] NULL,
	[ManualInputItemCode16] [nvarchar](16) NULL,
	[ManualInputLotNumber16] [nvarchar](16) NULL,
	[ManualInputLoadingAmount16] [real] NULL,
	[ManualInputItemCode17] [nvarchar](16) NULL,
	[ManualInputLotNumber17] [nvarchar](16) NULL,
	[ManualInputLoadingAmount17] [real] NULL,
	[ManualInputItemCode18] [nvarchar](16) NULL,
	[ManualInputLotNumber18] [nvarchar](16) NULL,
	[ManualInputLoadingAmount18] [real] NULL,
	[ManualInputItemCode19] [nvarchar](16) NULL,
	[ManualInputLotNumber19] [nvarchar](16) NULL,
	[ManualInputLoadingAmount19] [real] NULL,
	[ManualInputItemCode20] [nvarchar](16) NULL,
	[ManualInputLotNumber20] [nvarchar](16) NULL,
	[ManualInputLoadingAmount20] [real] NULL,
	[ManualInputItemCode21] [nvarchar](16) NULL,
	[ManualInputLotNumber21] [nvarchar](16) NULL,
	[ManualInputLoadingAmount21] [real] NULL,
	[ManualInputItemCode22] [nvarchar](16) NULL,
	[ManualInputLotNumber22] [nvarchar](16) NULL,
	[ManualInputLoadingAmount22] [real] NULL,
	[ManualInputItemCode23] [nvarchar](16) NULL,
	[ManualInputLotNumber23] [nvarchar](16) NULL,
	[ManualInputLoadingAmount23] [real] NULL,
	[ManualInputItemCode24] [nvarchar](16) NULL,
	[ManualInputLotNumber24] [nvarchar](16) NULL,
	[ManualInputLoadingAmount24] [real] NULL,
	[ManualInputItemCode25] [nvarchar](16) NULL,
	[ManualInputLotNumber25] [nvarchar](16) NULL,
	[ManualInputLoadingAmount25] [real] NULL,
	[ManualInputItemCode26] [nvarchar](16) NULL,
	[ManualInputLotNumber26] [nvarchar](16) NULL,
	[ManualInputLoadingAmount26] [real] NULL,
	[ManualInputItemCode27] [nvarchar](16) NULL,
	[ManualInputLotNumber27] [nvarchar](16) NULL,
	[ManualInputLoadingAmount27] [real] NULL,
	[ManualInputItemCode28] [nvarchar](16) NULL,
	[ManualInputLotNumber28] [nvarchar](16) NULL,
	[ManualInputLoadingAmount28] [real] NULL,
	[ManualInputItemCode29] [nvarchar](16) NULL,
	[ManualInputLotNumber29] [nvarchar](16) NULL,
	[ManualInputLoadingAmount29] [real] NULL,
	[ManualInputItemCode30] [nvarchar](16) NULL,
	[ManualInputLotNumber30] [nvarchar](16) NULL,
	[ManualInputLoadingAmount30] [real] NULL,
	[ManualInputItemCode31] [nvarchar](16) NULL,
	[ManualInputLotNumber31] [nvarchar](16) NULL,
	[ManualInputLoadingAmount31] [real] NULL,
	[ManualInputItemCode32] [nvarchar](16) NULL,
	[ManualInputLotNumber32] [nvarchar](16) NULL,
	[ManualInputLoadingAmount32] [real] NULL,
	[ManualInputItemCode33] [nvarchar](16) NULL,
	[ManualInputLotNumber33] [nvarchar](16) NULL,
	[ManualInputLoadingAmount33] [real] NULL,
	[ManualInputItemCode34] [nvarchar](16) NULL,
	[ManualInputLotNumber34] [nvarchar](16) NULL,
	[ManualInputLoadingAmount34] [real] NULL,
	[ManualInputItemCode35] [nvarchar](16) NULL,
	[ManualInputLotNumber35] [nvarchar](16) NULL,
	[ManualInputLoadingAmount35] [real] NULL,
	[ManualInputItemCode36] [nvarchar](16) NULL,
	[ManualInputLotNumber36] [nvarchar](16) NULL,
	[ManualInputLoadingAmount36] [real] NULL,
	[ManualInputItemCode37] [nvarchar](16) NULL,
	[ManualInputLotNumber37] [nvarchar](16) NULL,
	[ManualInputLoadingAmount37] [real] NULL,
	[ManualInputItemCode38] [nvarchar](16) NULL,
	[ManualInputLotNumber38] [nvarchar](16) NULL,
	[ManualInputLoadingAmount38] [real] NULL,
	[ManualInputItemCode39] [nvarchar](16) NULL,
	[ManualInputLotNumber39] [nvarchar](16) NULL,
	[ManualInputLoadingAmount39] [real] NULL,
	[ManualInputItemCode40] [nvarchar](16) NULL,
	[ManualInputLotNumber40] [nvarchar](16) NULL,
	[ManualInputLoadingAmount40] [real] NULL,
	[ManualInputItemCode41] [nvarchar](16) NULL,
	[ManualInputLotNumber41] [nvarchar](16) NULL,
	[ManualInputLoadingAmount41] [real] NULL,
	[ManualInputItemCode42] [nvarchar](16) NULL,
	[ManualInputLotNumber42] [nvarchar](16) NULL,
	[ManualInputLoadingAmount42] [real] NULL,
	[ManualInputItemCode43] [nvarchar](16) NULL,
	[ManualInputLotNumber43] [nvarchar](16) NULL,
	[ManualInputLoadingAmount43] [real] NULL,
	[ManualInputItemCode44] [nvarchar](16) NULL,
	[ManualInputLotNumber44] [nvarchar](16) NULL,
	[ManualInputLoadingAmount44] [real] NULL,
	[ManualInputItemCode45] [nvarchar](16) NULL,
	[ManualInputLotNumber45] [nvarchar](16) NULL,
	[ManualInputLoadingAmount45] [real] NULL,
	[ManualInputItemCode46] [nvarchar](16) NULL,
	[ManualInputLotNumber46] [nvarchar](16) NULL,
	[ManualInputLoadingAmount46] [real] NULL,
	[ManualInputItemCode47] [nvarchar](16) NULL,
	[ManualInputLotNumber47] [nvarchar](16) NULL,
	[ManualInputLoadingAmount47] [real] NULL,
	[ManualInputItemCode48] [nvarchar](16) NULL,
	[ManualInputLotNumber48] [nvarchar](16) NULL,
	[ManualInputLoadingAmount48] [real] NULL,
	[ManualInputItemCode49] [nvarchar](16) NULL,
	[ManualInputLotNumber49] [nvarchar](16) NULL,
	[ManualInputLoadingAmount49] [real] NULL,
	[ManualInputItemCode50] [nvarchar](16) NULL,
	[ManualInputLotNumber50] [nvarchar](16) NULL,
	[ManualInputLoadingAmount50] [real] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[MasterKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MaterialTableA]  WITH CHECK ADD FOREIGN KEY([ForeignKey])
REFERENCES [dbo].[ProductionResultsTable] ([ProductionOrderNumber])
GO

