USE [MES31]
GO

/****** Object:  Table [dbo].[SingleControlProcessTable]    Script Date: 2026/09/12 13:52:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SingleControlProcessTable](
	[MasterKey] [nvarchar](32) NOT NULL,
	[ForeignKey] [nvarchar](32) NULL,
	[LotNumber] [nvarchar](16) NOT NULL,
	[ItemCode] [nvarchar](16) NOT NULL,
	[StartDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[ManufacturingProcessName] [nvarchar](16) NOT NULL,
	[Weight] [real] NULL,
	[LiquidLevel] [real] NULL,
	[SourceTankName] [nvarchar](16) NULL,
	[PumpDelayTime] [real] NULL,
	[ValveDelayTime] [real] NULL,
	[PressureSelection] [int] NULL,
	[PressureTargetValue] [real] NULL,
	[TargetUpperLimitPressure] [real] NULL,
	[TargetLowerLimitPressure] [real] NULL,
	[CorrectionUpperLimitPressure] [real] NULL,
	[CorrectionLowerLimitPressure] [real] NULL,
	[CirculationFlowPathSelectionFlag] [int] NULL,
	[CirculationPumpStartupSpeed] [real] NULL,
	[CirculationPumpFrequency] [real] NULL,
	[CirculationPumpOperationTime] [int] NULL,
	[CirculationPumpStopWeight] [real] NULL,
	[CirculationPumpFrequencySetting_L] [real] NULL,
	[CirculationPumpTargetFrequency] [real] NULL,
	[CirculationPumpStartupTime] [int] NULL,
	[CirculationPumpStartupSpeed1] [real] NULL,
	[CirculationPumpStartupSpeed2] [real] NULL,
	[AgitatorFrequency] [real] NULL,
	[MixerOperationTime] [int] NULL,
	[MixerStopWeight] [real] NULL,
	[SourceTankPumpStartupSpeed] [real] NULL,
	[SourceTankPump1tageFrequency] [real] NULL,
	[SourceTankPump2stageFrequency] [real] NULL,
	[SourceTankPump2stageFrequencySwitchingWeight] [real] NULL,
	[SurfacePumpStartupSpeed] [real] NULL,
	[SurfacePumpFrequency] [real] NULL,
	[SurfacePumpCurrentMonitor_H] [real] NULL,
	[SurfacePumpCurrentMonitor_L] [real] NULL,
	[CorrectionSpeed] [real] NULL,
	[Timer] [int] NULL,
	[AmountOfStock] [real] NULL,
	[AmountOfExtrction] [real] NULL,
	[WasteVolume] [real] NULL,
	[ValveHalfopenWeight] [real] NULL,
	[DroopAmountSettingValue] [real] NULL,
	[TotalDischargePumpStopDelayTime] [real] NULL,
	[ControlCompletionDelayTime] [real] NULL,
	[UpperLimitAlarmPressure_H] [real] NULL,
	[LowerLimitAlarmPressure_L] [real] NULL,
	[UpperLimitAlarmPressure_HH] [real] NULL,
	[LowerLimitAlarmPressure_LL] [real] NULL,
	[WeightMonitoring] [real] NULL,
	[ManholeLockTimer] [int] NULL,
	[ManholeAlarmTimer] [int] NULL,
	[ManholeOpeningTime] [datetime] NULL,
	[ManholeClosingTime] [datetime] NULL,
	[ManholeOpenedHours] [int] NULL,
	[NumberOfManholesOpenedAndClosed] [int] NULL,
	[N2PressTimer1] [int] NULL,
	[N2PressTimer2] [int] NULL,
	[N2PressTimer3] [int] NULL,
	[WasteLiquidTypeFlag] [int] NULL,
	[NumberOfWashes] [int] NULL,
	[CirculationLineCleaningTime] [int] NULL,
	[BypassLineCirculationTime] [int] NULL,
	[ShowerBallCleaningTime] [int] NULL,
	[CirculatingLineFrequencySettingValue] [real] NULL,
	[BypassLineFrequencySettingValue] [real] NULL,
	[ShowerBallFrequencySettingValue] [real] NULL,
	[SamplingFlag] [int] NULL,
	[SourcePressureUpperLimitSettingValue] [real] NULL,
	[FillingMachineCirculationPumpOperationTime] [int] NULL,
	[BypassCirculationPumpOperationTime] [int] NULL,
	[FlowAccumulationCountSettingValue] [real] NULL,
	[MinimumContinuousFlowAccumulationCountSettingValue] [real] NULL,
	[TransferPumpDesignationCode] [int] NULL,
	[TransferPumpPowerSupplyDesignationCode] [int] NULL,
	[MixerDesignationCode] [int] NULL,
	[MixerPowerSupplyDesignationCode] [int] NULL,
	[FlowTargetValue] [real] NULL,
	[TargetUpperLimitFlow] [real] NULL,
	[TargetLowerLimitFlow] [real] NULL,
	[CorrectionUpperLimitFlow] [real] NULL,
	[CorrectionLowerLimitFlow] [real] NULL,
	[UpperLimitAlarmFlow_H] [real] NULL,
	[LowerLimitAlarmFlow_L] [real] NULL,
	[UpperLimitAlarmFlow_HH] [real] NULL,
	[LowerLimitAlarmFlow_LL] [real] NULL,
	[PumpDelayTime1] [real] NULL,
	[ValveDelayTime1] [real] NULL,
	[PreparationOrder1] [real] NULL,
	[SourceTankPumpStartupSpeed1] [real] NULL,
	[SourceTankPump1tageFrequency1] [real] NULL,
	[SourceTankPump2stageFrequency1] [real] NULL,
	[SourceTankPump2stageFrequencySwitchingWeight1] [real] NULL,
	[AmountOfStock1] [real] NULL,
	[DroopAmountSettingValue1] [real] NULL,
	[PumpDelayTime2] [real] NULL,
	[ValveDelayTime2] [real] NULL,
	[PreparationOrder2] [real] NULL,
	[SourceTankPumpStartupSpeed2] [real] NULL,
	[SourceTankPump1tageFrequency2] [real] NULL,
	[SourceTankPump2stageFrequency2] [real] NULL,
	[SourceTankPump2stageFrequencySwitchingWeight2] [real] NULL,
	[AmountOfStock2] [real] NULL,
	[DroopAmountSettingValue2] [real] NULL,
	[PumpDelayTime3] [real] NULL,
	[ValveDelayTime3] [real] NULL,
	[PreparationOrder3] [real] NULL,
	[SourceTankPumpStartupSpeed3] [real] NULL,
	[SourceTankPump1tageFrequency3] [real] NULL,
	[SourceTankPump2stageFrequency3] [real] NULL,
	[SourceTankPump2stageFrequencySwitchingWeight3] [real] NULL,
	[AmountOfStock3] [real] NULL,
	[DroopAmountSettingValue3] [real] NULL,
	[PumpDelayTime_Washing] [real] NULL,
	[ValveDelayTime_Washing] [real] NULL,
	[WashingPumpStartupSpeed_Washing] [real] NULL,
	[WashingPumpFrequency_Washing] [real] NULL,
	[WashingPumpOperationTime_Washing1] [real] NULL,
	[WashingPumpOperationTime_Washing2] [real] NULL,
	[WashingPumpOperationTime_Washing3] [real] NULL,
	[PumpDelayTime_Collect] [real] NULL,
	[ValveDelayTime_Collect] [real] NULL,
	[CollectPumpStartupSpeed_Collect] [real] NULL,
	[CollectPumpFrequency_Collect] [real] NULL,
	[CollectPumpOperationTime_Collect] [real] NULL,
	[WashingPumpDesignationCode] [int] NULL,
	[WashingPumpPowerSupplyDesignationCode] [int] NULL,
	[WashingPumpStartupSpeed] [real] NULL,
	[WashingPumpFrequency] [real] NULL,
	[NumberOfWashes1] [real] NULL,
	[NumberOfWashes2] [real] NULL,
	[NumberOfWashes3] [real] NULL,
	[N2FillingTimer] [int] NULL,
	[OxygenConcentrationSettingValue] [real] NULL,
	[AirRemovalTime1] [int] NULL,
	[AirRemovalTime2] [int] NULL,
	[ShowerBallLineFlag] [int] NULL,
	[FlowAccumulationCountPresentValue] [real] NULL,
	[MinimumContinuousFlowAccumulationCountPresentValue] [real] NULL,
	[FillingMachineValveOpeningAndClosingPattern] [int] NULL,
	[FillingMachineSelectFlag] [int] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[MasterKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SingleControlProcessTable]  WITH CHECK ADD FOREIGN KEY([ForeignKey])
REFERENCES [dbo].[ProductionOrderTable] ([ProductionOrderNumber])
GO

